language: d

d:
  - dmd-2.070.0
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - ldc-0.17.0-beta1
  - ldc-0.16.1

env:
  - VIBED_DRIVER=libevent BUILD_EXAMPLE=1 RUN_TEST=1
  - VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=1

matrix:
  exclude:
    - d: ldc-0.16.1
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=1

script: ./travis-ci.sh

services:
  - mongodb
  - redis-server

sudo: false
